/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package product;

import io.swagger.model.Error;
import io.swagger.model.Product;
import io.swagger.model.Productresponse1;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-05T14:21:34.873+05:30")

@Api(value = "product", description = "the product API")
public interface ProductApi {

    @ApiOperation(value = "ProductByProductId_DELETE", nickname = "productByProductIdDELETE", notes = "Delete a Product by productId", tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = ""),
        @ApiResponse(code = 404, message = "TODO: Add error message", response = Error.class) })
    @RequestMapping(value = "/product/{productId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> productByProductIdDELETE(@ApiParam(value = "",required=true) @PathVariable("productId") String productId);


    @ApiOperation(value = "ProductByProductId_GET", nickname = "productByProductIdGET", notes = "Get a Product by productId", response = Product.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Product.class),
        @ApiResponse(code = 404, message = "TODO: Add error message", response = Error.class) })
    @RequestMapping(value = "/product/{productId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Product> productByProductIdGET(@ApiParam(value = "",required=true) @PathVariable("productId") String productId);


    @ApiOperation(value = "ProductByProductId_POST", nickname = "productByProductIdPOST", notes = "Product using Username & Password", response = Productresponse1.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Productresponse1.class),
        @ApiResponse(code = 400, message = "TODO: Add error message", response = Error.class) })
    @RequestMapping(value = "/product/{productId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Productresponse1> productByProductIdPOST(@ApiParam(value = "",required=true) @PathVariable("productId") String productId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Product body);


    @ApiOperation(value = "ProductByProductId_PUT", nickname = "productByProductIdPUT", notes = "Update a Product by productId", response = Product.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Product.class),
        @ApiResponse(code = 404, message = "TODO: Add error message", response = Error.class) })
    @RequestMapping(value = "/product/{productId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Product> productByProductIdPUT(@ApiParam(value = "",required=true) @PathVariable("productId") String productId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Product body);


    @ApiOperation(value = "Product_GET", nickname = "productGET", notes = "Get a list of Product", response = Product.class, responseContainer = "List", tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Product.class, responseContainer = "List") })
    @RequestMapping(value = "/product",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Product>> productGET(@ApiParam(value = "Get List of Tenant Info based on a given Tenant Name") @Valid @RequestParam(value = "productName", required = false) String productName,@ApiParam(value = "Get List of Tenant Info based on a given Tenant Email") @Valid @RequestParam(value = "productCategory", required = false) String productCategory);


    @ApiOperation(value = "Product_POST", nickname = "productPOST", notes = "Add a new Product", response = Productresponse1.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Productresponse1.class) })
    @RequestMapping(value = "/product",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Productresponse1> productPOST(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Product body);

}
